SELECT b.year,
b.course_id,
b.degree_id,
sum(b.total) AS total,
sum(b.total_men) AS total_men,
sum(b.total_women) AS total_women,
sum(b.total_native) AS total_native,
sum(total_native_men) AS total_native_men,
sum(total_native_women) AS total_native_women,
sum(total_asian) AS total_asian,
sum(total_asian_men) AS total_asian_men,
sum(total_asian_women) AS total_asian_women,
sum(total_black) AS total_black,
sum(total_black_men) AS total_black_men,
sum(total_black_women) AS total_black_women,
sum(total_hispanic) AS total_hispanic,
sum(total_hispanic_men) AS total_hispanic_men,
sum(total_hispanic_women) AS total_hispanic_women,
sum(total_hawaiian) AS total_hawaiian,
sum(total_hawaiian_men) AS total_hawaiian_men,
sum(total_hawaiian_women) AS total_hawaiian_women,
sum(total_white) AS total_white,
sum(total_white_men) AS total_white_men,
sum(total_white_women) AS total_white_women,
sum(total_multi) AS total_multi,
sum(total_multi_men) AS total_multi_men,
sum(total_multi_women) AS total_multi_women,
sum(total_unknown) AS total_unknown,
sum(total_unknown_men) AS total_unknown_men,
sum(total_unknown_women) AS total_unknown_women,
sum(total_nonresident) AS total_nonresident ,
sum(total_nonresident_men) AS total_nonresident_men,
sum(total_nonresident_women) AS total_nonresident_women
FROM ipeds.grads_yucd b
GROUP BY b.year, b.course_id, b.degree_id;