SELECT yu.year,
   yu.university,
   ycu.cip,
   ycu.grads_total,
   round(1.0 * ycu.grads_total::numeric / NULLIF(yu.grads_total, 0)::numeric, 4) AS pct_total,
   round(1.0 * ycu.grads_men::numeric / NULLIF(yu.grads_men, 0)::numeric, 4) AS pct_men,
   round(1.0 * ycu.grads_women::numeric / NULLIF(yu.grads_women, 0)::numeric, 4) AS pct_women,
   round(1.0 * ycu.grads_native::numeric / NULLIF(yu.grads_native, 0)::numeric, 4) AS pct_native,
   round(1.0 * ycu.grads_native_men::numeric / NULLIF(yu.grads_native_men, 0)::numeric, 4) AS pct_native_men,
   round(1.0 * ycu.grads_native_women::numeric / NULLIF(yu.grads_native_women, 0)::numeric, 4) AS pct_native_women,
   round(1.0 * ycu.grads_asian::numeric / NULLIF(yu.grads_asian, 0)::numeric, 4) AS pct_asian,
   round(1.0 * ycu.grads_asian_men::numeric / NULLIF(yu.grads_asian_men, 0)::numeric, 4) AS pct_asian_men,
   round(1.0 * ycu.grads_asian_women::numeric / NULLIF(yu.grads_asian_women, 0)::numeric, 4) AS pct_asian_women,
   round(1.0 * ycu.grads_black::numeric / NULLIF(yu.grads_black, 0)::numeric, 4) AS pct_black,
   round(1.0 * ycu.grads_black_men::numeric / NULLIF(yu.grads_black_men, 0)::numeric, 4) AS pct_black_men,
   round(1.0 * ycu.grads_black_women::numeric / NULLIF(yu.grads_black_women, 0)::numeric, 4) AS pct_black_women,
   round(1.0 * ycu.grads_hispanic::numeric / NULLIF(yu.grads_hispanic, 0)::numeric, 4) AS pct_hispanic,
   round(1.0 * ycu.grads_hispanic_men::numeric / NULLIF(yu.grads_hispanic_men, 0)::numeric, 4) AS pct_hispanic_men,
   round(1.0 * ycu.grads_hispanic_women::numeric / NULLIF(yu.grads_hispanic_women, 0)::numeric, 4) AS pct_hispanic_women,
   round(1.0 * ycu.grads_hawaiian::numeric / NULLIF(yu.grads_hawaiian, 0)::numeric, 4) AS pct_hawaiian,
   round(1.0 * ycu.grads_hawaiian_men::numeric / NULLIF(yu.grads_hawaiian_men, 0)::numeric, 4) AS pct_hawaiian_men,
   round(1.0 * ycu.grads_hawaiian_women::numeric / NULLIF(yu.grads_hawaiian_women, 0)::numeric, 4) AS pct_hawaiian_women,
   round(1.0 * ycu.grads_white::numeric / NULLIF(yu.grads_white, 0)::numeric, 4) AS pct_white,
   round(1.0 * ycu.grads_white_men::numeric / NULLIF(yu.grads_white_men, 0)::numeric, 4) AS pct_white_men,
   round(1.0 * ycu.grads_white_women::numeric / NULLIF(yu.grads_white_women, 0)::numeric, 4) AS pct_white_women,
   round(1.0 * ycu.grads_multi::numeric / NULLIF(yu.grads_multi, 0)::numeric, 4) AS pct_multi,
   round(1.0 * ycu.grads_multi_men::numeric / NULLIF(yu.grads_multi_men, 0)::numeric, 4) AS pct_multi_men,
   round(1.0 * ycu.grads_multi_women::numeric / NULLIF(yu.grads_multi_women, 0)::numeric, 4) AS pct_multi_women,
   round(1.0 * ycu.grads_unknown::numeric / NULLIF(yu.grads_unknown, 0)::numeric, 4) AS pct_unknown,
   round(1.0 * ycu.grads_unknown_men::numeric / NULLIF(yu.grads_unknown_men, 0)::numeric, 4) AS pct_unknown_men,
   round(1.0 * ycu.grads_unknown_women::numeric / NULLIF(yu.grads_unknown_women, 0)::numeric, 4) AS pct_unknown_women,
   round(1.0 * ycu.grads_nonresident::numeric / NULLIF(yu.grads_nonresident, 0)::numeric, 4) AS pct_nonresident,
   round(1.0 * ycu.grads_nonresident_men::numeric / NULLIF(yu.grads_nonresident_men, 0)::numeric, 4) AS pct_nonresident_men,
   round(1.0 * ycu.grads_nonresident_women::numeric / NULLIF(yu.grads_nonresident_women, 0)::numeric, 4) AS pct_nonresident_women
  FROM ipeds.grads_ycu ycu
    LEFT JOIN ipeds.grads_yu_orig yu ON yu.year = ycu.year AND yu.university = ycu.university;
